### ISSUE TITLE
Panic in Packet UnmarshalBinary

### ISSUE THREAD

**Issue by 0x34d** [facebookincubator/tacquito#8]
``` go
func TestPacket(t *testing.T) {

	decoded := &Packet{}
	decoded.UnmarshalBinary([]byte("000"))
}
```
Run -> `go test -run TestPacket`

### backtrace
```log
goroutine 12 [running]:
testing.tRunner.func1.2({0x887460, 0xc00002c1c8})
	/usr/lib/golang/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1529 +0x39f
panic({0x887460, 0xc00002c1c8})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/facebookincubator/tacquito.(*Packet).UnmarshalBinary(0xc00006a740, {0xc000028310, 0x52a4a5?, 0x3})
	/home/0x34d/project/tacquito/packet.go:126 +0x205
github.com/facebookincubator/tacquito.TestPacket(0xc000007a00?)
	/home/0x34d/project/tacquito/packet_test.go:450 +0x56
testing.tRunner(0xc000007d40, 0x8ec2b0)
	/usr/lib/golang/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/facebookincubator/tacquito	0.007s
```

**Comment by RollerMatic** [comment]
Thanks for raising this ! We have added a check for smaller packets in b24e2224f4442680240d9d76337432e85f41a1ec
